package com.example.rojad.projectlogin.model;

import java.util.List;

public class Question {
    public int questionId; //Each question has unique id generated by db rowid
    public String question; //string data enter by user
    public int postedBy; //postBy represent question posted BY
    public List<Answer> answers; // List of answers i.e., suggestions provided by counsoler
    public Contact user; // User info used at the time of Admin side for displaying name of the owner of the post


}
